### ISSUE TITLE
個人チャットでラズパイIDをデータベース消去

### ISSUE THREAD

**Issue by take-cantik** [jphacks/E_2005#8]
- 友達を削除するとき
- 何か削除の類のものを打ったとき
どれにするか要相談

**Comment by syu-kwsk** [comment]
https://developers.line.biz/ja/reference/messaging-api/#unfollow-event
↑のフォロー解除イベントみるとブロックしたときだけイベント発生しそう
友達削除したときにイベント発生するかはわからんな。
メッセージによってbot側から退出するとかはなさそう。

**Comment by ryutaro-kimura** [comment]
でけた
